### ISSUE TITLE
Enforce type checking

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/phylum-ci#238]
## Description

A portion of the Python code base makes use of type annotations. The entire code base should do so, to reduce bugs, improve quality, and enhance the IDE experience.

## Additional Details

Use one of the more common type checkers - `mypy`, `pyright`, or `pyre` - and enforce standards by adding the checker to QA as a pre-commit hook.

Consider adding this setting to the `ruff` config for `isort`:

```toml
[tool.ruff.isort]
force-sort-within-sections = true
required-imports = ["from __future__ import annotations"]
```

## References

* [PEP 526 - Syntax for Variable Annotations](https://peps.python.org/pep-0526/)
* [PEP 3107 – Function Annotations](https://peps.python.org/pep-3107/)
* [PEP 484 – Type Hints](https://peps.python.org/pep-0484/)

## Acceptance Criteria

- [ ] All Python code is annotated with types
- [ ] Type checking is enforced in QA
- [ ] `ruff` rules for `ANN` (flake8-annotations) are no longer disabled
- [ ] `ruff` rules for `TCH` (flake8-type-checking) are no longer disabled
- [ ] Documentation is updated
