### ISSUE TITLE
Coordinate phylum-ci Docker image releases with new CLI releases

### ISSUE THREAD

**Issue by maxrake** [phylum-dev/phylum-ci#50]
## Overview

**Is your feature request related to a problem? Please describe.**
The release process of `phylum-ci` is currently the only time a new Docker image is created and pushed to the Docker Hub `phylumio/phylum-ci` repository. That means that the version of the CLI that gets included there can become out of date/sync if there are additional CLI releases published in the mean time. While there are options exposed in `phylum-ci` (e.g., `--phylum-release` and `--force-install`) to allow users to override the version of the CLI used, it may not be obvious to users when they would want to do so.

**Describe the solution you'd like**
Detect when a new Phylum CLI release is published and create a new `phylum-ci` image with that CLI version to be pushed to the Docker Hub repository as the `latest` tag.

**Describe alternatives you've considered**
* Remove the CLI from the image and install it on demand as part of the container execution
  * This will add time to the execution
  * This may mean the integrations and CLI are not tested together before real-world use
* Maybe create and push new images on a schedule, always pulling the `latest` CLI release

## Additional context

This issue is relevant so long as the CLI is included in the Docker image. It is possible that the CLI will be removed in favor of making direct Phylum API calls.

It might be necessary to revisit the Docker image tagging format. That is, the tag might need to contain information about the version of Phylum CLI *and* the version of `phylum-ci` that are contained in the image.

It might be necessary to coordinate with the CLI repository to sync up the workflows.

## Acceptance criteria

- [x] A new `phylum-ci` Docker image is created and pushed to the registry when a new Phylum CLI release is published
- [x] Documentation is updated

**Comment by maxrake** [comment]
It turns out the following syntax is invalid for a GitHub Actions workflow:

```yaml
# both of these forms fail the syntax check
if: ! contains(github.ref, 'rc')
if: !contains(github.ref, 'rc')
```

This was discovered after merging the new Docker workflow and [attempting to trigger it](https://github.com/phylum-dev/phylum-ci/actions/runs/2497648487/workflow)

After searching the docs and coming up empty, a [GitHub Community Forum post](https://github.community/t/expression-syntax-for-not-startswith/17040) for this issue (but for `startswith` instead of `contains`) showed the way to go:

```yaml
# it works if you enclose everything in double quotes
if: "!contains(github.ref, 'rc')"

# this also works and reads more cleanly to my eye
if: contains(github.ref, 'rc') != true
```
